apiVersion: v1
kind: Namespace
metadata:
  name: playground-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: poc-api-svc
  namespace: playground-k8s
  labels:
    app: poc-api
    tier: app
    version: v1
spec:
  type: ClusterIP #LoadBalancer only Cloud
  ports:
    - port: 80
  selector:
    app: poc-api
    tier: app
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poc-api
  namespace: playground-k8s  
  labels:
    app: poc-api
    tier: app
    version: v1
spec:
  selector:
    matchLabels:
      app: poc-api
      tier: app
      version: v1
  replicas: 2
  template:
    metadata:
      labels:
        app: poc-api
        tier: app
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: poc-api
          image: jcmds/poc-api
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 15
            periodSeconds: 30
            httpGet:
              path: /swagger/index.html
              port: 80    
          resources:
            requests:
              cpu: 25m
              memory: 200Mi
          imagePullPolicy: IfNotPresent           
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%       
